### ISSUE TITLE
Production query

### ISSUE THREAD

**Issue by telezoic** [afeld/magickly#54]
Hi there,

At my organization we’re deploying a metatdata aggregation app, currently in a demo phase. The app calls on http://magickly.afeld.me/ to process thumbnails for display. We’re working on deploying our own instance of magickly for this, but aren’t quite there yet. The readme makes a reference to using the magickly demo in production . . . is this available/advisable?

Thanks!

**Comment by afeld** [comment]
It's not, in that I make no guarantees about uptime or performance. Let me know how it goes though!
